### ISSUE TITLE
geometry_msg 질문

### ISSUE THREAD

**Issue by jjh946** [Road-Balance/gcamp-ros2-seminar#2]
안녕하세요 세미나를 듣고 다른 작업들도 해보고 있습니다. 
지금 ros2를 사용하려고 하다가 roswiki에 있는 페키지 중 ros1만 지원하는 것이 있어서 ros melodic을 18.04에서 사용중입니다. 

http://wiki.ros.org/visp_auto_tracker
여기의 페키지를 사용하여 geometry_msgs/PoseStamp 를 가져오는 과정이고 이를 변수로 이용하여 모터를 제어하는 것이 최종적인 모표입니다.

`rostopic echo /visp_auto_tracker/object_position`
을 이용하여 메세지를 터미널 상에서 확인 하는 것 까지는 완료를 하였는데

![image](https://user-images.githubusercontent.com/85427212/141665901-237305fc-ab81-4703-911d-b7f640738dd9.png)

이 메세지를 확인하는 것 만이 아니라 변수로 사용하여 다른 node에 명령하는 방법을 잘 모르겠습니다 rosbag나 rosmsg 이런것들을 활용해야 하는 것인가요?

**Comment by kimsooyoung** [comment]
* `geometry_msgs/PoseStamp`를 subscribe하고
* subscribe한 데이터를 통해 모터를 제어하는

위와 같은 node를 새로 프로그래밍해야 할 것 같습니다.
관련 프로그래밍은 **ROS tutorial**을 참고하시기 바랍니다.

**Comment by jjh946** [comment]
> * `geometry_msgs/PoseStamp`를 subscribe하고
> * subscribe한 데이터를 통해 모터를 제어하는
> 
> 위와 같은 node를 새로 프로그래밍해야 할 것 같습니다. 관련 프로그래밍은 **ROS tutorial**을 참고하시기 바랍니다.

답변 감사합니다! 시도해보겠습니다
